# Generated by Django 3.2.12 on 2022-04-27 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 16, 43, 38, 572245, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
