# Generated by Django 3.2.12 on 2022-05-03 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 15, 42, 1, 178270, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
